#!/bin/sh
set -e
linkname=~/.ipython/profile_default/history.sqlite
target=~/history/ipython.sqlite
if test -f "$linkname" && ! test -e "$target"; then
  mv "$linkname" "$target"
elif test -L "$linkname" ; then
  sleep 0
elif test -e "$linkname"; then
  echo You need to manually link
  echo "$linkname"
  echo to
  echo "$target"
  exit 1
elif test -d ~/.ipython/profile_default; then
  ln -s "$target" "$linkname"
fi
