#!/bin/sh
set -e
dotfile=~/.historian
historydir=~/history

mkdir -p "$historydir"

# Run one-time configurations
for file in install/modules/*; do
  "$file"
done

# Add things to the profile
if test -e "$dotfile"; then
  echo "$dotfile" already exists.
  exit 1
fi
cp -R historian "$dotfile"
echo ". $dotfile/profile" >> ~/.profile
