#!/bin/sh
set -e
dotfile=~/.historian
historydir=~/history

mkdir -p "$historydir"

# Run one-time configurations
for file in install/modules/*; do
  "$file"
done

# Add things to the profile
mkdir -p "$dotfile/sources"
cp historian_writer/profile "$dotfile"
cp historian_writer/sources/* "$dotfile/sources"
# echo ". $dotfile/profile" >> ~/.profile
